# Generated by Django 3.2.6 on 2021-08-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastfood',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
